# Generated by Django 4.0.4 on 2022-06-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
