# Generated by Django 4.0.4 on 2022-06-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
