# Generated by Django 4.0.4 on 2022-06-30 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_product_index_together_remove_category_slug_and_more'),
        ('cart', '0003_rename_shop_id_order_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Общая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsinorder',
            name='rental_period',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Срок аренды'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('products', models.ManyToManyField(blank=True, related_name='related_cart', to='cart.cartproduct')),
            ],
        ),
    ]
