# Generated by Django 4.0.4 on 2022-07-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_productsinorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='cart.cart', verbose_name='Корзина'),
            preserve_default=False,
        ),
    ]
