# Generated by Django 4.0.4 on 2022-07-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_cart_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productsinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductsInOrder',
        ),
    ]
